### ISSUE TITLE
error switching namespace with F5 shortcut

### ISSUE THREAD

**Issue by marcosamorim** [cloudnativelabs/kube-shell#39]
Hi,

When I hit F5 to switch between namespace an error appears on logs.

```
2017-09-04 13:52:32,344 [WARNING] kubeshell.kubeshell _:113 - failed namespace switching
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/kubeshell/kubeshell.py", line 110, in _
    KubeConfig.switch_to_next_namespace(Kubeshell.namespace)
  File "/usr/local/lib/python2.7/site-packages/kubeshell/kubeshell.py", line 77, in switch_to_next_namespace
    namespace_resources = completer.get_resources("namespace")
AttributeError: 'KubectlCompleter' object has no attribute 'get_resources'
```

I'm running kube-shell 0.0.21 on iTerm2 
OS: Mac Os 10.12.6

Any solution for this issue?

Thanks.

**Comment by murali-reddy** [comment]
@marcosamorim sorry seems like regression in 0.0.21 release. i will try to fix it.

**Comment by marcosamorim** [comment]
@murali-reddy Thanks for the quick answer. Doing some investigation here, seems that method has been moved to KubectlClient class now.

**Comment by zachaller** [comment]
This has not been pushed out to pip

**Comment by murali-reddy** [comment]
Please try the latest release (0.0.22](https://pypi.python.org/pypi/kube-shell/0.0.22).
