### ISSUE TITLE
ImportError: cannot import name NewConnectionError

### ISSUE THREAD

**Issue by ilwyiworld** [cloudnativelabs/kube-shell#41]
[root@lv101 gluster_k8s_vloume]# kube-shell
Traceback (most recent call last):
  File "/usr/bin/kube-shell", line 7, in <module>
    from kubeshell.main import cli
  File "/usr/lib/python2.7/site-packages/kubeshell/main.py", line 6, in <module>
    from kubeshell.kubeshell import Kubeshell
  File "/usr/lib/python2.7/site-packages/kubeshell/kubeshell.py", line 10, in <module>
    from kubeshell.completer import KubectlCompleter
  File "/usr/lib/python2.7/site-packages/kubeshell/completer.py", line 11, in <module>
    from kubeshell.client import KubernetesClient
  File "/usr/lib/python2.7/site-packages/kubeshell/client.py", line 1, in <module>
    from urllib3.exceptions import NewConnectionError, ConnectTimeoutError, MaxRetryError
ImportError: cannot import name NewConnectionError

**Comment by fgiloux** [comment]
"sudo pip install --upgrade urllib3" fixed the issue for me
