### ISSUE TITLE
F5 namespace switch doesn't work (still or again?)

### ISSUE THREAD

**Issue by k0nstantinv** [cloudnativelabs/kube-shell#42]
Hello, First of all thanks for you work! 

I have been using kube-shell few days and everything it's OK, but namespace switcher doesn't work. There is no errors or something else, just no reaction when i press F5

My system: Ubuntu 16.04
My python: 2.7.12
My kube-shell: 0.0.21 (latest)

I saw similar issue https://github.com/cloudnativelabs/kube-shell/issues/39
Is there a way to fix it or need to wait for the next release?

**Comment by murali-reddy** [comment]
Apologies for not giving attention this issue. I have released 0.0.22 version. Please give it a try and see if issue is resolved.

**Comment by k0nstantinv** [comment]
@murali-reddy kube-shell completely doesn't work after update:
```kube-shell> 1Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/local/lib/python2.7/dist-packages/kubeshell/completer.py", line 42, in get_completionsExit                                                                                                            
    _, _, suggestions = self.parser.parse_tokens(tokens)
AttributeError: 'KubectlCompleter' object has no attribute 'parser'

kube-shell> 1

**Comment by murali-reddy** [comment]
@k0nstantinv can you please try 0.0.23?

**Comment by lynchc** [comment]
same issue with 0.0.23

**Comment by Stono** [comment]
Ditto, this doesn't work for me (nor does server side completion).

**Comment by wasimj** [comment]
Likewise. Changing Namespaces with F5 doesn't work.

**Comment by mabushey** [comment]
`F4` and `F5` do not work, however `F9` and `F10` do.

**Comment by hasrobin** [comment]
Upgrading to 0.0.23 resolved this issue for me.

macOS 10.14.5
python 2.7.15

**Comment by kaka-milan-22** [comment]
me,too, F4 F5 not working ,F9 do.

**Comment by perskes** [comment]
Switching with F5 seems to need a "kick" sometimes.

I switched the namespace with kubens while in kube-shell. After that I was able to cycle through my namespaces with F5 again.
It's a bit frustrating, but it works and it stays like that for as long as the shell (not just kube-shell) is active.
