### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by jjangga0214** [cloudnativelabs/kube-shell#78]
When I type `kube-shell`, it fails.

System info: python 3.7.3, pip 19.0.3, ubuntu 19.04, 64 bits 

```bash
Traceback (most recent call last):
  File "/home/gilchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/gilchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/gilchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.4.5 (/home/gilchan/.local/lib/python3.7/site-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.6'), {'pyasn1-modules'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gilchan/.pyenv/versions/3.7.3/bin/kube-shell", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/gilchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/gilchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/gilchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/gilchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/gilchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/gilchan/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.4.5 (/home/gilchan/.local/lib/python3.7/site-packages), Requirement.parse('pyasn1<0.5.0,>=0.4.6'), {'pyasn1-modules'})
```

**Comment by sumit-anantwar** [comment]
I am also getting the same error
